server:
  port: 8080
  servlet:
    contextPath: /agentService





spring:
  application:
    name: Spring Profiles

  flyway:
    baselineOnMigrate: true
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update # <-- this is your "spring.jpa.hibernate.ddl-auto=update"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: true
tenants:
  configurations:
    uhf:
      url: jdbc:mysql://localhost:3306/sd
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
    netwell:
      url: jdbc:mysql://localhost:3306/sd1
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
    innovation:
      url: jdbc:mysql://localhost:3306/sd2
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
    aec:
      url: jdbc:mysql://localhost:3306/sd3?&useSSL=false
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver

    ichra:
      url: jdbc:mysql://localhost:3306/sd4
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
jwt:
  secret: silentboy
#
#    #----- Agent userpool details--------------
#
#    agent_source: UHF-Agent portal
#    cognito_agent_userpool: us-east-2_5HWivIrrT
#
#    #---------Token API username and password-----
#    token_api_username: Innovation
#    token_api_password: Innovation
#
#    token_api_url: https://dev.fabric.carynhealth.com/api/v1/login
#    agent_registration_api: https://dev.fabric.carynhealth.com/api/v4.0/memberportal/register
#
#
#    USPS_API_URL: https://secure.shippingapis.com/ShippingAPI.dll
#    USPS_USER_ID: 935USTGL7449

































































































